# \u542F\u7528\u65E5\u5FD7\u989C\u8272
spring.output.ansi.enabled=always
logging.level.root=INFO
# mapper \u63A5\u53E3\u6240\u5728\u7684\u5305\u8BBE\u7F6E\u4E3A debug
#logging.level.com.\u00D7\u00D7\u00D7.mapper=DEBUG
## \u5728\u5F53\u524D\u9879\u76EE\u4E0B\u751F\u6210\u65E5\u5FD7\u6587\u4EF6
#logging.file=./logs/\u00D7\u00D7\u00D7.log
#logging.pattern.console=%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %clr(%logger){cyan} %clr(%msg%n){green}
#logging.pattern.file=%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
